# Build settings
permalink: /:year-:month-:day-:title.html
url: ""
author: stardust
plugins: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
# commentscomponent: disqus or gitalk or closecomments
commentscomponent: closecomments
excerpt_separator: <!--more-->
paginate: 100
# Sass
sass:
  style: compressed
